services:
  - type: web
    name: txs-console-center
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn txs_console_center.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: txs_console_center.settings
    staticPublishPath: staticfiles
    routes:
      - type: v1
        name: api
        path: /api/*
        allowOrigins:
          - "*"
    healthCheckPath: "/admin"
    autoDeploy: true

  - type: static
    name: static-assets
    staticPublishPath: staticfiles
    routes:
      - type: v1
        path: /static/*
        allowOrigins:
          - "*"
      - type: v1
        path: /media/*
        allowOrigins:
          - "*"
    healthCheckPath: "/"
