# Generated by Django 4.2 on 2025-05-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectupload',
            old_name='guthub_link',
            new_name='github_link',
        ),
    ]
