# Generated by Django 4.2 on 2025-05-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('location', models.JSONField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('last_visited', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
